name: Run React Tests

# Trigger the workflow on push to the main branch or on pull requests
on:
  push:
    branches:
      - main
      - CI_
  pull_request:
    branches:
      - main

# Define the jobs that will be run
jobs:
  test:
    # The type of virtual machine to use
    runs-on: ubuntu-latest

    # Steps to run within the job
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Navigate to the client directory
      - name: Navigate to client directory
        run: cd client

      # Cache node_modules in the client folder
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: client/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies in the client folder using npm ci
      - name: Install dependencies
        run: npm ci
        working-directory: client

      # Run your tests inside the client folder
      - name: Run tests
        run: npm test -- --watchAll=false
        working-directory: client