name: Run React Tests

# Trigger the workflow on push to the main branch or on pull requests
on:
  push:
    branches:
      - main
      - CI_
  pull_request:
    branches:
      - main

# Define the jobs that will be run
jobs:
  test:
    # The type of virtual machine to use
    runs-on: ubuntu-latest

    # Steps to run within the job
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies using npm
      - name: Install dependencies
        run: npm install

      # Run your tests
      - name: Run tests
        run: npm test -- --watchAll=false